# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestReactNavigation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestReactNavigation

  target 'TestReactNavigation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestReactNavigationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  rn_path = '../node_modules/react-native'
  pod 'Yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"

  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'aliyun-oss-react-native', :path => '../node_modules/aliyun-oss-react-native'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

end
